/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package flyway.db.migration.app

import flyway.db.migration.utilities.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    println("Testing!")
}
